name: Deploy DefectDojo to Azure App Service

on:
  push:
    branches:
      - master  # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run collectstatic
      run: |
        python manage.py collectstatic --noinput

    - name: Run database migrations
      run: |
        python manage.py migrate
      env:
       DJANGO_SETTINGS_MODULE: dojo.settings
       DD_DATABASE_ENGINE: django.db.backends.postgresql
       DD_DATABASE_NAME: defectdojo
       DD_DATABASE_USER: defectdojo
       DD_DATABASE_PASSWORD: ${{ secrets.DD_DATABASE_PASSWORD }}
       DD_DATABASE_HOST: clinical-ai-defectdojo-server.postgres.database.azure.com
       DD_DATABASE_PORT: 5432

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'Clinical-AI-Defectdojo'  # Azure App Service name
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .

